name: CI
on:
  workflow_dispatch:
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          touch .env
          echo 'A2A_PASSWORD=${{ secrets.A2A_PASSWORD }}' >> .env
          echo 'A2A_USERNAME=${{ secrets.A2A_USERNAME }}' >> .env
          echo 'FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }}' >> .env
          yarn xxx
      - name: Upload error screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/
